from . import test_dental_logic
from . import test_patient
from . import test_recall
from . import test_treatment
from . import test_tariff
from . import test_lpd
from . import test_odontogram
from . import test_plan
from . import test_prescription
from . import test_questionnaire
from . import test_imaging
